# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'comrado3.ui'
##
## Created by: Qt User Interface Compiler version 6.9.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QGroupBox, QLCDNumber,
    QLabel, QMainWindow, QPushButton, QSizePolicy,
    QStackedWidget, QTabWidget, QToolButton, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1024, 600)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QSize(1024, 600))
        MainWindow.setMaximumSize(QSize(1024, 600))
        MainWindow.setTabShape(QTabWidget.TabShape.Rounded)
        MainWindow.setDockNestingEnabled(False)
        self.action = QAction(MainWindow)
        self.action.setObjectName(u"action")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.System_frame = QFrame(self.centralwidget)
        self.System_frame.setObjectName(u"System_frame")
        self.System_frame.setGeometry(QRect(10, 10, 251, 571))
        self.System_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.System_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.Editor_button = QPushButton(self.System_frame)
        self.Editor_button.setObjectName(u"Editor_button")
        self.Editor_button.setGeometry(QRect(10, 460, 231, 41))
        self.lcdNumber = QLCDNumber(self.System_frame)
        self.lcdNumber.setObjectName(u"lcdNumber")
        self.lcdNumber.setGeometry(QRect(100, 60, 111, 23))
        self.Bar_frame = QFrame(self.centralwidget)
        self.Bar_frame.setObjectName(u"Bar_frame")
        self.Bar_frame.setGeometry(QRect(270, 500, 730, 81))
        self.Bar_frame.setAutoFillBackground(False)
        self.Bar_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.Bar_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.Bar_groupBox = QGroupBox(self.Bar_frame)
        self.Bar_groupBox.setObjectName(u"Bar_groupBox")
        self.Bar_groupBox.setGeometry(QRect(0, 0, 730, 81))
        self.Bar_groupBox.setStyleSheet(u"border: 4px double #444;        /* \u0422\u043e\u043b\u0449\u0438\u043d\u0430, \u0441\u0442\u0438\u043b\u044c \u0438 \u0446\u0432\u0435\u0442 \u0440\u0430\u043c\u043a\u0438 */\n"
"    border-radius: 6px;             /* \u0417\u0430\u043a\u0440\u0443\u0433\u043b\u0435\u043d\u0438\u0435 \u0443\u0433\u043b\u043e\u0432 */\n"
"    background-color: #3c3c3c;      /* \u0426\u0432\u0435\u0442 \u0444\u043e\u043d\u0430 */\n"
"    padding: 5px;                  /* \u0412\u043d\u0443\u0442\u0440\u0435\u043d\u043d\u0438\u0439 \u043e\u0442\u0441\u0442\u0443\u043f */\n"
"    margin-top: 0 px;               /* \u041e\u0442\u0441\u0442\u0443\u043f \u043d\u0430\u0434 \u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043a\u043e\u043c */")
        self.Bar_groupBox.setFlat(False)
        self.Button_stackedWidget = QStackedWidget(self.centralwidget)
        self.Button_stackedWidget.setObjectName(u"Button_stackedWidget")
        self.Button_stackedWidget.setEnabled(True)
        self.Button_stackedWidget.setGeometry(QRect(270, 10, 750, 450))
        self.Button_stackedWidget.setMinimumSize(QSize(750, 450))
        self.Button_stackedWidget.setMaximumSize(QSize(750, 450))
        self.Button_stackedWidget.setBaseSize(QSize(0, 0))
        self.Button_stackedWidget.setCursor(QCursor(Qt.CursorShape.ArrowCursor))
        self.Button_stackedWidget.setFocusPolicy(Qt.FocusPolicy.ClickFocus)
        self.Button_stackedWidget.setContextMenuPolicy(Qt.ContextMenuPolicy.CustomContextMenu)
        self.Button_stackedWidget.setLocale(QLocale(QLocale.Russian, QLocale.Russia))
        self.Button_stackedWidget.setFrameShape(QFrame.Shape.NoFrame)
        self.Button_stackedWidget.setLineWidth(1)
        self.page_1 = QWidget()
        self.page_1.setObjectName(u"page_1")
        self.Button_frame_01 = QFrame(self.page_1)
        self.Button_frame_01.setObjectName(u"Button_frame_01")
        self.Button_frame_01.setGeometry(QRect(10, 0, 730, 440))
        self.Button_frame_01.setMaximumSize(QSize(730, 440))
        self.Button_frame_01.setStyleSheet(u"gridline-color: rgb(255, 170, 255);\n"
"border-color: rgb(255, 0, 255);")
        self.Button_frame_01.setFrameShape(QFrame.Shape.StyledPanel)
        self.Button_frame_01.setFrameShadow(QFrame.Shadow.Raised)
        self.ToolButton_01 = QToolButton(self.Button_frame_01)
        self.ToolButton_01.setObjectName(u"ToolButton_01")
        self.ToolButton_01.setGeometry(QRect(50, 20, 128, 128))
        self.ToolButton_01.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.ToolButton_01.setIconSize(QSize(96, 96))
        self.ToolButton_01.setCheckable(False)
        self.ToolButton_01.setChecked(False)
        self.ToolButton_01.setAutoRepeatDelay(600)
        self.ToolButton_01.setAutoRepeatInterval(300)
        self.ToolButton_01.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.ToolButton_02 = QToolButton(self.Button_frame_01)
        self.ToolButton_02.setObjectName(u"ToolButton_02")
        self.ToolButton_02.setGeometry(QRect(220, 20, 128, 128))
        self.ToolButton_02.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.ToolButton_02.setIconSize(QSize(96, 96))
        self.ToolButton_02.setCheckable(False)
        self.ToolButton_02.setChecked(False)
        self.ToolButton_02.setAutoRepeatDelay(600)
        self.ToolButton_02.setAutoRepeatInterval(300)
        self.ToolButton_02.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.ToolButton_03 = QToolButton(self.Button_frame_01)
        self.ToolButton_03.setObjectName(u"ToolButton_03")
        self.ToolButton_03.setGeometry(QRect(390, 20, 128, 128))
        self.ToolButton_03.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.ToolButton_03.setIconSize(QSize(96, 96))
        self.ToolButton_03.setCheckable(False)
        self.ToolButton_03.setChecked(False)
        self.ToolButton_03.setAutoRepeatDelay(600)
        self.ToolButton_03.setAutoRepeatInterval(300)
        self.ToolButton_03.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.ToolButton_04 = QToolButton(self.Button_frame_01)
        self.ToolButton_04.setObjectName(u"ToolButton_04")
        self.ToolButton_04.setGeometry(QRect(560, 20, 128, 128))
        self.ToolButton_04.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.ToolButton_04.setIconSize(QSize(96, 96))
        self.ToolButton_04.setCheckable(False)
        self.ToolButton_04.setChecked(False)
        self.ToolButton_04.setAutoRepeatDelay(600)
        self.ToolButton_04.setAutoRepeatInterval(300)
        self.ToolButton_04.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.ToolButton_05 = QToolButton(self.Button_frame_01)
        self.ToolButton_05.setObjectName(u"ToolButton_05")
        self.ToolButton_05.setGeometry(QRect(50, 160, 128, 128))
        self.ToolButton_05.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.ToolButton_05.setIconSize(QSize(96, 96))
        self.ToolButton_05.setCheckable(False)
        self.ToolButton_05.setChecked(False)
        self.ToolButton_05.setAutoRepeatDelay(600)
        self.ToolButton_05.setAutoRepeatInterval(300)
        self.ToolButton_05.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.ToolButton_06 = QToolButton(self.Button_frame_01)
        self.ToolButton_06.setObjectName(u"ToolButton_06")
        self.ToolButton_06.setGeometry(QRect(220, 160, 128, 128))
        self.ToolButton_06.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.ToolButton_06.setIconSize(QSize(96, 96))
        self.ToolButton_06.setCheckable(False)
        self.ToolButton_06.setChecked(False)
        self.ToolButton_06.setAutoRepeatDelay(600)
        self.ToolButton_06.setAutoRepeatInterval(300)
        self.ToolButton_06.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.ToolButton_07 = QToolButton(self.Button_frame_01)
        self.ToolButton_07.setObjectName(u"ToolButton_07")
        self.ToolButton_07.setGeometry(QRect(390, 160, 128, 128))
        self.ToolButton_07.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.ToolButton_07.setIconSize(QSize(96, 96))
        self.ToolButton_07.setCheckable(False)
        self.ToolButton_07.setChecked(False)
        self.ToolButton_07.setAutoRepeatDelay(600)
        self.ToolButton_07.setAutoRepeatInterval(300)
        self.ToolButton_07.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.ToolButton_08 = QToolButton(self.Button_frame_01)
        self.ToolButton_08.setObjectName(u"ToolButton_08")
        self.ToolButton_08.setGeometry(QRect(560, 160, 128, 128))
        self.ToolButton_08.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.ToolButton_08.setIconSize(QSize(96, 96))
        self.ToolButton_08.setCheckable(False)
        self.ToolButton_08.setChecked(False)
        self.ToolButton_08.setAutoRepeatDelay(600)
        self.ToolButton_08.setAutoRepeatInterval(300)
        self.ToolButton_08.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.ToolButton_09 = QToolButton(self.Button_frame_01)
        self.ToolButton_09.setObjectName(u"ToolButton_09")
        self.ToolButton_09.setGeometry(QRect(50, 300, 128, 128))
        self.ToolButton_09.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.ToolButton_09.setIconSize(QSize(96, 96))
        self.ToolButton_09.setCheckable(False)
        self.ToolButton_09.setChecked(False)
        self.ToolButton_09.setAutoRepeatDelay(600)
        self.ToolButton_09.setAutoRepeatInterval(300)
        self.ToolButton_09.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.ToolButton_10 = QToolButton(self.Button_frame_01)
        self.ToolButton_10.setObjectName(u"ToolButton_10")
        self.ToolButton_10.setGeometry(QRect(220, 300, 128, 128))
        self.ToolButton_10.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.ToolButton_10.setIconSize(QSize(96, 96))
        self.ToolButton_10.setCheckable(False)
        self.ToolButton_10.setChecked(False)
        self.ToolButton_10.setAutoRepeatDelay(600)
        self.ToolButton_10.setAutoRepeatInterval(300)
        self.ToolButton_10.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.ToolButton_11 = QToolButton(self.Button_frame_01)
        self.ToolButton_11.setObjectName(u"ToolButton_11")
        self.ToolButton_11.setGeometry(QRect(390, 300, 128, 128))
        self.ToolButton_11.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.ToolButton_11.setIconSize(QSize(96, 96))
        self.ToolButton_11.setCheckable(False)
        self.ToolButton_11.setChecked(False)
        self.ToolButton_11.setAutoRepeatDelay(600)
        self.ToolButton_11.setAutoRepeatInterval(300)
        self.ToolButton_11.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.ToolButton_12 = QToolButton(self.Button_frame_01)
        self.ToolButton_12.setObjectName(u"ToolButton_12")
        self.ToolButton_12.setGeometry(QRect(560, 300, 128, 128))
        self.ToolButton_12.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.ToolButton_12.setIconSize(QSize(96, 96))
        self.ToolButton_12.setCheckable(False)
        self.ToolButton_12.setChecked(False)
        self.ToolButton_12.setAutoRepeatDelay(600)
        self.ToolButton_12.setAutoRepeatInterval(300)
        self.ToolButton_12.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.Button_stackedWidget.addWidget(self.page_1)
        self.Page_control_frame = QFrame(self.centralwidget)
        self.Page_control_frame.setObjectName(u"Page_control_frame")
        self.Page_control_frame.setGeometry(QRect(520, 460, 255, 35))
        self.Page_control_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.Page_control_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.Current_page_label = QLabel(self.Page_control_frame)
        self.Current_page_label.setObjectName(u"Current_page_label")
        self.Current_page_label.setGeometry(QRect(100, 5, 60, 25))
        self.Current_page_label.setContextMenuPolicy(Qt.ContextMenuPolicy.ActionsContextMenu)
        self.Current_page_label.setFrameShape(QFrame.Shape.StyledPanel)
        self.Current_page_label.setFrameShadow(QFrame.Shadow.Plain)
        self.Current_page_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.NextButton_main = QPushButton(self.Page_control_frame)
        self.NextButton_main.setObjectName(u"NextButton_main")
        self.NextButton_main.setGeometry(QRect(170, 5, 75, 25))
        self.BackButton_main = QPushButton(self.Page_control_frame)
        self.BackButton_main.setObjectName(u"BackButton_main")
        self.BackButton_main.setGeometry(QRect(10, 5, 75, 25))
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        self.Button_stackedWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"El Gui Comrado v 0.4", None))
        self.action.setIconText("")
        self.Editor_button.setText(QCoreApplication.translate("MainWindow", u"Editor", None))
        self.Bar_groupBox.setTitle("")
        self.ToolButton_01.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.ToolButton_02.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.ToolButton_03.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.ToolButton_04.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.ToolButton_05.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.ToolButton_06.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.ToolButton_07.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.ToolButton_08.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.ToolButton_09.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.ToolButton_10.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.ToolButton_11.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.ToolButton_12.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.Current_page_label.setText("")
        self.NextButton_main.setText(QCoreApplication.translate("MainWindow", u"TempNext", None))
        self.BackButton_main.setText(QCoreApplication.translate("MainWindow", u"TempBack", None))
    # retranslateUi

