# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'comrado3.ui'
##
## Created by: Qt User Interface Compiler version 6.9.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QGridLayout, QHBoxLayout,
    QLabel, QMainWindow, QPushButton, QSizePolicy,
    QStackedWidget, QTabWidget, QToolButton, QVBoxLayout,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setWindowModality(Qt.WindowModality.NonModal)
        MainWindow.resize(1024, 650)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QSize(1024, 650))
        MainWindow.setMaximumSize(QSize(1024, 650))
        MainWindow.setTabletTracking(True)
        MainWindow.setFocusPolicy(Qt.FocusPolicy.TabFocus)
        MainWindow.setContextMenuPolicy(Qt.ContextMenuPolicy.NoContextMenu)
        MainWindow.setWindowTitle(u"EL GUI COMRADO v 0.5.3")
        MainWindow.setInputMethodHints(Qt.InputMethodHint.ImhNone)
        MainWindow.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonIconOnly)
        MainWindow.setTabShape(QTabWidget.TabShape.Rounded)
        MainWindow.setDockNestingEnabled(False)
        self.action = QAction(MainWindow)
        self.action.setObjectName(u"action")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setEnabled(True)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setFocusPolicy(Qt.FocusPolicy.TabFocus)
        self.layoutWidget = QWidget(self.centralwidget)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(0, 0, 1026, 576))
        self.MainLayout = QHBoxLayout(self.layoutWidget)
        self.MainLayout.setSpacing(5)
        self.MainLayout.setObjectName(u"MainLayout")
        self.MainLayout.setContentsMargins(4, 2, 4, 2)
        self.BarBut_Layout = QVBoxLayout()
        self.BarBut_Layout.setSpacing(4)
        self.BarBut_Layout.setObjectName(u"BarBut_Layout")
        self.BarBut_Layout.setContentsMargins(4, 4, 4, 4)
        self.Widget_bar_frame = QFrame(self.layoutWidget)
        self.Widget_bar_frame.setObjectName(u"Widget_bar_frame")
        sizePolicy.setHeightForWidth(self.Widget_bar_frame.sizePolicy().hasHeightForWidth())
        self.Widget_bar_frame.setSizePolicy(sizePolicy)
        self.Widget_bar_frame.setMinimumSize(QSize(290, 450))
        self.Widget_bar_frame.setMaximumSize(QSize(290, 450))
        self.Widget_bar_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.Widget_bar_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.verticalLayout = QVBoxLayout(self.Widget_bar_frame)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.Bar_target_1 = QFrame(self.Widget_bar_frame)
        self.Bar_target_1.setObjectName(u"Bar_target_1")
        self.Bar_target_1.setEnabled(True)
        self.Bar_target_1.setMinimumSize(QSize(270, 80))
        self.Bar_target_1.setMaximumSize(QSize(270, 80))
        self.Bar_target_1.setFrameShape(QFrame.Shape.StyledPanel)
        self.Bar_target_1.setFrameShadow(QFrame.Shadow.Raised)

        self.verticalLayout.addWidget(self.Bar_target_1)

        self.Bar_target_2 = QFrame(self.Widget_bar_frame)
        self.Bar_target_2.setObjectName(u"Bar_target_2")
        self.Bar_target_2.setMinimumSize(QSize(270, 80))
        self.Bar_target_2.setMaximumSize(QSize(270, 80))
        self.Bar_target_2.setFrameShape(QFrame.Shape.StyledPanel)
        self.Bar_target_2.setFrameShadow(QFrame.Shadow.Raised)

        self.verticalLayout.addWidget(self.Bar_target_2)

        self.Bar_target_3 = QFrame(self.Widget_bar_frame)
        self.Bar_target_3.setObjectName(u"Bar_target_3")
        self.Bar_target_3.setMinimumSize(QSize(270, 80))
        self.Bar_target_3.setMaximumSize(QSize(270, 80))
        self.Bar_target_3.setFrameShape(QFrame.Shape.StyledPanel)
        self.Bar_target_3.setFrameShadow(QFrame.Shadow.Raised)

        self.verticalLayout.addWidget(self.Bar_target_3)

        self.Bar_target_4 = QFrame(self.Widget_bar_frame)
        self.Bar_target_4.setObjectName(u"Bar_target_4")
        self.Bar_target_4.setMinimumSize(QSize(270, 80))
        self.Bar_target_4.setMaximumSize(QSize(270, 80))
        self.Bar_target_4.setFrameShape(QFrame.Shape.StyledPanel)
        self.Bar_target_4.setFrameShadow(QFrame.Shadow.Raised)

        self.verticalLayout.addWidget(self.Bar_target_4)

        self.Bar_target_5 = QFrame(self.Widget_bar_frame)
        self.Bar_target_5.setObjectName(u"Bar_target_5")
        self.Bar_target_5.setMinimumSize(QSize(270, 80))
        self.Bar_target_5.setMaximumSize(QSize(270, 80))
        self.Bar_target_5.setFrameShape(QFrame.Shape.StyledPanel)
        self.Bar_target_5.setFrameShadow(QFrame.Shadow.Raised)

        self.verticalLayout.addWidget(self.Bar_target_5)


        self.BarBut_Layout.addWidget(self.Widget_bar_frame)

        self.Editor_frame = QFrame(self.layoutWidget)
        self.Editor_frame.setObjectName(u"Editor_frame")
        self.Editor_frame.setMinimumSize(QSize(290, 46))
        self.Editor_frame.setMaximumSize(QSize(290, 46))
        self.Editor_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.Editor_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.horizontalLayout = QHBoxLayout(self.Editor_frame)
        self.horizontalLayout.setSpacing(12)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(6, 5, 6, 5)
        self.Editor_bar_button = QPushButton(self.Editor_frame)
        self.Editor_bar_button.setObjectName(u"Editor_bar_button")
        sizePolicy.setHeightForWidth(self.Editor_bar_button.sizePolicy().hasHeightForWidth())
        self.Editor_bar_button.setSizePolicy(sizePolicy)
        self.Editor_bar_button.setMinimumSize(QSize(0, 30))

        self.horizontalLayout.addWidget(self.Editor_bar_button)

        self.Change_Button = QPushButton(self.Editor_frame)
        self.Change_Button.setObjectName(u"Change_Button")
        sizePolicy.setHeightForWidth(self.Change_Button.sizePolicy().hasHeightForWidth())
        self.Change_Button.setSizePolicy(sizePolicy)
        self.Change_Button.setMinimumSize(QSize(0, 30))
        self.Change_Button.setCheckable(True)
        self.Change_Button.setChecked(False)
        self.Change_Button.setFlat(False)

        self.horizontalLayout.addWidget(self.Change_Button)

        self.Editor_button = QPushButton(self.Editor_frame)
        self.Editor_button.setObjectName(u"Editor_button")
        sizePolicy.setHeightForWidth(self.Editor_button.sizePolicy().hasHeightForWidth())
        self.Editor_button.setSizePolicy(sizePolicy)
        self.Editor_button.setMinimumSize(QSize(0, 30))

        self.horizontalLayout.addWidget(self.Editor_button)


        self.BarBut_Layout.addWidget(self.Editor_frame)

        self.Page_control_frame = QFrame(self.layoutWidget)
        self.Page_control_frame.setObjectName(u"Page_control_frame")
        sizePolicy.setHeightForWidth(self.Page_control_frame.sizePolicy().hasHeightForWidth())
        self.Page_control_frame.setSizePolicy(sizePolicy)
        self.Page_control_frame.setMinimumSize(QSize(280, 46))
        self.Page_control_frame.setMaximumSize(QSize(290, 46))
        self.Page_control_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.Page_control_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.horizontalLayout_2 = QHBoxLayout(self.Page_control_frame)
        self.horizontalLayout_2.setSpacing(12)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(4, 5, 4, 5)
        self.BackButton_main = QPushButton(self.Page_control_frame)
        self.BackButton_main.setObjectName(u"BackButton_main")
        sizePolicy.setHeightForWidth(self.BackButton_main.sizePolicy().hasHeightForWidth())
        self.BackButton_main.setSizePolicy(sizePolicy)
        self.BackButton_main.setMinimumSize(QSize(0, 30))
        self.BackButton_main.setMaximumSize(QSize(16777215, 40))

        self.horizontalLayout_2.addWidget(self.BackButton_main)

        self.Current_page_label = QLabel(self.Page_control_frame)
        self.Current_page_label.setObjectName(u"Current_page_label")
        self.Current_page_label.setMinimumSize(QSize(0, 30))
        self.Current_page_label.setMaximumSize(QSize(16777215, 40))
        self.Current_page_label.setContextMenuPolicy(Qt.ContextMenuPolicy.ActionsContextMenu)
        self.Current_page_label.setFrameShape(QFrame.Shape.StyledPanel)
        self.Current_page_label.setFrameShadow(QFrame.Shadow.Plain)
        self.Current_page_label.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.horizontalLayout_2.addWidget(self.Current_page_label)

        self.NextButton_main = QPushButton(self.Page_control_frame)
        self.NextButton_main.setObjectName(u"NextButton_main")
        sizePolicy.setHeightForWidth(self.NextButton_main.sizePolicy().hasHeightForWidth())
        self.NextButton_main.setSizePolicy(sizePolicy)
        self.NextButton_main.setMinimumSize(QSize(0, 30))
        self.NextButton_main.setMaximumSize(QSize(16777215, 40))

        self.horizontalLayout_2.addWidget(self.NextButton_main)


        self.BarBut_Layout.addWidget(self.Page_control_frame)


        self.MainLayout.addLayout(self.BarBut_Layout)

        self.Button_stackedWidget = QStackedWidget(self.layoutWidget)
        self.Button_stackedWidget.setObjectName(u"Button_stackedWidget")
        self.Button_stackedWidget.setEnabled(True)
        self.Button_stackedWidget.setMinimumSize(QSize(710, 570))
        self.Button_stackedWidget.setMaximumSize(QSize(710, 570))
        self.Button_stackedWidget.setBaseSize(QSize(0, 0))
        font = QFont()
        font.setPointSize(5)
        self.Button_stackedWidget.setFont(font)
        self.Button_stackedWidget.setCursor(QCursor(Qt.CursorShape.ArrowCursor))
        self.Button_stackedWidget.setFocusPolicy(Qt.FocusPolicy.TabFocus)
        self.Button_stackedWidget.setContextMenuPolicy(Qt.ContextMenuPolicy.CustomContextMenu)
        self.Button_stackedWidget.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.Button_stackedWidget.setLocale(QLocale(QLocale.Russian, QLocale.Russia))
        self.Button_stackedWidget.setFrameShape(QFrame.Shape.StyledPanel)
        self.Button_stackedWidget.setFrameShadow(QFrame.Shadow.Raised)
        self.Button_stackedWidget.setLineWidth(1)
        self.page_1 = QWidget()
        self.page_1.setObjectName(u"page_1")
        self.page_1.setEnabled(True)
        self.page_1.setMinimumSize(QSize(710, 570))
        self.page_1.setMaximumSize(QSize(710, 570))
        self.page_1.setFocusPolicy(Qt.FocusPolicy.TabFocus)
        self.page_1.setToolTipDuration(-1)
        self.page_1.setAutoFillBackground(False)
        self.Button_frame_01 = QFrame(self.page_1)
        self.Button_frame_01.setObjectName(u"Button_frame_01")
        self.Button_frame_01.setEnabled(True)
        self.Button_frame_01.setGeometry(QRect(0, 0, 710, 570))
        sizePolicy.setHeightForWidth(self.Button_frame_01.sizePolicy().hasHeightForWidth())
        self.Button_frame_01.setSizePolicy(sizePolicy)
        self.Button_frame_01.setMinimumSize(QSize(710, 570))
        self.Button_frame_01.setMaximumSize(QSize(710, 570))
        self.Button_frame_01.setFocusPolicy(Qt.FocusPolicy.TabFocus)
        self.Button_frame_01.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.Button_frame_01.setFrameShape(QFrame.Shape.StyledPanel)
        self.Button_frame_01.setFrameShadow(QFrame.Shadow.Raised)
        self.Button_frame_01.setLineWidth(1)
        self.Button_frame_01.setMidLineWidth(1)
        self.gridLayout = QGridLayout(self.Button_frame_01)
        self.gridLayout.setSpacing(10)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.ToolButton_01 = QToolButton(self.Button_frame_01)
        self.ToolButton_01.setObjectName(u"ToolButton_01")
        self.ToolButton_01.setEnabled(True)
        sizePolicy.setHeightForWidth(self.ToolButton_01.sizePolicy().hasHeightForWidth())
        self.ToolButton_01.setSizePolicy(sizePolicy)
        self.ToolButton_01.setMinimumSize(QSize(150, 150))
        self.ToolButton_01.setMaximumSize(QSize(150, 150))
        self.ToolButton_01.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.ToolButton_01.setIconSize(QSize(96, 96))
        self.ToolButton_01.setCheckable(False)
        self.ToolButton_01.setChecked(False)
        self.ToolButton_01.setAutoRepeatDelay(600)
        self.ToolButton_01.setAutoRepeatInterval(300)
        self.ToolButton_01.setPopupMode(QToolButton.ToolButtonPopupMode.DelayedPopup)
        self.ToolButton_01.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)

        self.gridLayout.addWidget(self.ToolButton_01, 0, 0, 1, 1)

        self.ToolButton_02 = QToolButton(self.Button_frame_01)
        self.ToolButton_02.setObjectName(u"ToolButton_02")
        self.ToolButton_02.setEnabled(True)
        sizePolicy.setHeightForWidth(self.ToolButton_02.sizePolicy().hasHeightForWidth())
        self.ToolButton_02.setSizePolicy(sizePolicy)
        self.ToolButton_02.setMinimumSize(QSize(150, 150))
        self.ToolButton_02.setMaximumSize(QSize(150, 150))
        self.ToolButton_02.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.ToolButton_02.setIconSize(QSize(96, 96))
        self.ToolButton_02.setCheckable(False)
        self.ToolButton_02.setChecked(False)
        self.ToolButton_02.setAutoRepeatDelay(600)
        self.ToolButton_02.setAutoRepeatInterval(300)
        self.ToolButton_02.setPopupMode(QToolButton.ToolButtonPopupMode.DelayedPopup)
        self.ToolButton_02.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)

        self.gridLayout.addWidget(self.ToolButton_02, 0, 1, 1, 1)

        self.ToolButton_03 = QToolButton(self.Button_frame_01)
        self.ToolButton_03.setObjectName(u"ToolButton_03")
        self.ToolButton_03.setEnabled(True)
        sizePolicy.setHeightForWidth(self.ToolButton_03.sizePolicy().hasHeightForWidth())
        self.ToolButton_03.setSizePolicy(sizePolicy)
        self.ToolButton_03.setMinimumSize(QSize(150, 150))
        self.ToolButton_03.setMaximumSize(QSize(150, 150))
        self.ToolButton_03.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.ToolButton_03.setIconSize(QSize(96, 96))
        self.ToolButton_03.setCheckable(False)
        self.ToolButton_03.setChecked(False)
        self.ToolButton_03.setAutoRepeatDelay(600)
        self.ToolButton_03.setAutoRepeatInterval(300)
        self.ToolButton_03.setPopupMode(QToolButton.ToolButtonPopupMode.DelayedPopup)
        self.ToolButton_03.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)

        self.gridLayout.addWidget(self.ToolButton_03, 0, 2, 1, 1)

        self.ToolButton_04 = QToolButton(self.Button_frame_01)
        self.ToolButton_04.setObjectName(u"ToolButton_04")
        self.ToolButton_04.setEnabled(True)
        sizePolicy.setHeightForWidth(self.ToolButton_04.sizePolicy().hasHeightForWidth())
        self.ToolButton_04.setSizePolicy(sizePolicy)
        self.ToolButton_04.setMinimumSize(QSize(150, 150))
        self.ToolButton_04.setMaximumSize(QSize(150, 150))
        self.ToolButton_04.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.ToolButton_04.setIconSize(QSize(96, 96))
        self.ToolButton_04.setCheckable(False)
        self.ToolButton_04.setChecked(False)
        self.ToolButton_04.setAutoRepeatDelay(600)
        self.ToolButton_04.setAutoRepeatInterval(300)
        self.ToolButton_04.setPopupMode(QToolButton.ToolButtonPopupMode.DelayedPopup)
        self.ToolButton_04.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)

        self.gridLayout.addWidget(self.ToolButton_04, 0, 3, 1, 1)

        self.ToolButton_05 = QToolButton(self.Button_frame_01)
        self.ToolButton_05.setObjectName(u"ToolButton_05")
        self.ToolButton_05.setEnabled(True)
        sizePolicy.setHeightForWidth(self.ToolButton_05.sizePolicy().hasHeightForWidth())
        self.ToolButton_05.setSizePolicy(sizePolicy)
        self.ToolButton_05.setMinimumSize(QSize(150, 150))
        self.ToolButton_05.setMaximumSize(QSize(150, 150))
        self.ToolButton_05.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.ToolButton_05.setIconSize(QSize(96, 96))
        self.ToolButton_05.setCheckable(False)
        self.ToolButton_05.setChecked(False)
        self.ToolButton_05.setAutoRepeatDelay(600)
        self.ToolButton_05.setAutoRepeatInterval(300)
        self.ToolButton_05.setPopupMode(QToolButton.ToolButtonPopupMode.DelayedPopup)
        self.ToolButton_05.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)

        self.gridLayout.addWidget(self.ToolButton_05, 1, 0, 1, 1)

        self.ToolButton_06 = QToolButton(self.Button_frame_01)
        self.ToolButton_06.setObjectName(u"ToolButton_06")
        self.ToolButton_06.setEnabled(True)
        sizePolicy.setHeightForWidth(self.ToolButton_06.sizePolicy().hasHeightForWidth())
        self.ToolButton_06.setSizePolicy(sizePolicy)
        self.ToolButton_06.setMinimumSize(QSize(150, 150))
        self.ToolButton_06.setMaximumSize(QSize(150, 150))
        self.ToolButton_06.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.ToolButton_06.setIconSize(QSize(96, 96))
        self.ToolButton_06.setCheckable(False)
        self.ToolButton_06.setChecked(False)
        self.ToolButton_06.setAutoRepeatDelay(600)
        self.ToolButton_06.setAutoRepeatInterval(300)
        self.ToolButton_06.setPopupMode(QToolButton.ToolButtonPopupMode.DelayedPopup)
        self.ToolButton_06.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)

        self.gridLayout.addWidget(self.ToolButton_06, 1, 1, 1, 1)

        self.ToolButton_07 = QToolButton(self.Button_frame_01)
        self.ToolButton_07.setObjectName(u"ToolButton_07")
        self.ToolButton_07.setEnabled(True)
        sizePolicy.setHeightForWidth(self.ToolButton_07.sizePolicy().hasHeightForWidth())
        self.ToolButton_07.setSizePolicy(sizePolicy)
        self.ToolButton_07.setMinimumSize(QSize(150, 150))
        self.ToolButton_07.setMaximumSize(QSize(150, 150))
        self.ToolButton_07.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.ToolButton_07.setIconSize(QSize(96, 96))
        self.ToolButton_07.setCheckable(False)
        self.ToolButton_07.setChecked(False)
        self.ToolButton_07.setAutoRepeatDelay(600)
        self.ToolButton_07.setAutoRepeatInterval(300)
        self.ToolButton_07.setPopupMode(QToolButton.ToolButtonPopupMode.DelayedPopup)
        self.ToolButton_07.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)

        self.gridLayout.addWidget(self.ToolButton_07, 1, 2, 1, 1)

        self.ToolButton_08 = QToolButton(self.Button_frame_01)
        self.ToolButton_08.setObjectName(u"ToolButton_08")
        self.ToolButton_08.setEnabled(True)
        sizePolicy.setHeightForWidth(self.ToolButton_08.sizePolicy().hasHeightForWidth())
        self.ToolButton_08.setSizePolicy(sizePolicy)
        self.ToolButton_08.setMinimumSize(QSize(150, 150))
        self.ToolButton_08.setMaximumSize(QSize(150, 150))
        self.ToolButton_08.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.ToolButton_08.setIconSize(QSize(96, 96))
        self.ToolButton_08.setCheckable(False)
        self.ToolButton_08.setChecked(False)
        self.ToolButton_08.setAutoRepeatDelay(600)
        self.ToolButton_08.setAutoRepeatInterval(300)
        self.ToolButton_08.setPopupMode(QToolButton.ToolButtonPopupMode.DelayedPopup)
        self.ToolButton_08.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)

        self.gridLayout.addWidget(self.ToolButton_08, 1, 3, 1, 1)

        self.ToolButton_09 = QToolButton(self.Button_frame_01)
        self.ToolButton_09.setObjectName(u"ToolButton_09")
        self.ToolButton_09.setEnabled(True)
        sizePolicy.setHeightForWidth(self.ToolButton_09.sizePolicy().hasHeightForWidth())
        self.ToolButton_09.setSizePolicy(sizePolicy)
        self.ToolButton_09.setMinimumSize(QSize(150, 150))
        self.ToolButton_09.setMaximumSize(QSize(150, 150))
        self.ToolButton_09.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.ToolButton_09.setIconSize(QSize(96, 96))
        self.ToolButton_09.setCheckable(False)
        self.ToolButton_09.setChecked(False)
        self.ToolButton_09.setAutoRepeatDelay(600)
        self.ToolButton_09.setAutoRepeatInterval(300)
        self.ToolButton_09.setPopupMode(QToolButton.ToolButtonPopupMode.DelayedPopup)
        self.ToolButton_09.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)

        self.gridLayout.addWidget(self.ToolButton_09, 2, 0, 1, 1)

        self.ToolButton_10 = QToolButton(self.Button_frame_01)
        self.ToolButton_10.setObjectName(u"ToolButton_10")
        self.ToolButton_10.setEnabled(True)
        sizePolicy.setHeightForWidth(self.ToolButton_10.sizePolicy().hasHeightForWidth())
        self.ToolButton_10.setSizePolicy(sizePolicy)
        self.ToolButton_10.setMinimumSize(QSize(150, 150))
        self.ToolButton_10.setMaximumSize(QSize(150, 150))
        self.ToolButton_10.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.ToolButton_10.setIconSize(QSize(96, 96))
        self.ToolButton_10.setCheckable(False)
        self.ToolButton_10.setChecked(False)
        self.ToolButton_10.setAutoRepeatDelay(600)
        self.ToolButton_10.setAutoRepeatInterval(300)
        self.ToolButton_10.setPopupMode(QToolButton.ToolButtonPopupMode.DelayedPopup)
        self.ToolButton_10.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)

        self.gridLayout.addWidget(self.ToolButton_10, 2, 1, 1, 1)

        self.ToolButton_11 = QToolButton(self.Button_frame_01)
        self.ToolButton_11.setObjectName(u"ToolButton_11")
        self.ToolButton_11.setEnabled(True)
        sizePolicy.setHeightForWidth(self.ToolButton_11.sizePolicy().hasHeightForWidth())
        self.ToolButton_11.setSizePolicy(sizePolicy)
        self.ToolButton_11.setMinimumSize(QSize(150, 150))
        self.ToolButton_11.setMaximumSize(QSize(150, 150))
        self.ToolButton_11.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.ToolButton_11.setIconSize(QSize(96, 96))
        self.ToolButton_11.setCheckable(False)
        self.ToolButton_11.setChecked(False)
        self.ToolButton_11.setAutoRepeatDelay(600)
        self.ToolButton_11.setAutoRepeatInterval(300)
        self.ToolButton_11.setPopupMode(QToolButton.ToolButtonPopupMode.DelayedPopup)
        self.ToolButton_11.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)

        self.gridLayout.addWidget(self.ToolButton_11, 2, 2, 1, 1)

        self.ToolButton_12 = QToolButton(self.Button_frame_01)
        self.ToolButton_12.setObjectName(u"ToolButton_12")
        self.ToolButton_12.setEnabled(True)
        sizePolicy.setHeightForWidth(self.ToolButton_12.sizePolicy().hasHeightForWidth())
        self.ToolButton_12.setSizePolicy(sizePolicy)
        self.ToolButton_12.setMinimumSize(QSize(150, 150))
        self.ToolButton_12.setMaximumSize(QSize(150, 150))
        self.ToolButton_12.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.ToolButton_12.setIconSize(QSize(96, 96))
        self.ToolButton_12.setCheckable(False)
        self.ToolButton_12.setChecked(False)
        self.ToolButton_12.setAutoRepeatDelay(600)
        self.ToolButton_12.setAutoRepeatInterval(300)
        self.ToolButton_12.setPopupMode(QToolButton.ToolButtonPopupMode.DelayedPopup)
        self.ToolButton_12.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)

        self.gridLayout.addWidget(self.ToolButton_12, 2, 3, 1, 1)

        self.Button_stackedWidget.addWidget(self.page_1)

        self.MainLayout.addWidget(self.Button_stackedWidget)

        self.Music_bttn = QPushButton(self.centralwidget)
        self.Music_bttn.setObjectName(u"Music_bttn")
        self.Music_bttn.setGeometry(QRect(480, 600, 75, 41))
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        self.Button_stackedWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
#if QT_CONFIG(tooltip)
        MainWindow.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.action.setIconText("")
        self.Editor_bar_button.setText(QCoreApplication.translate("MainWindow", u"Bar Editor", None))
        self.Change_Button.setText(QCoreApplication.translate("MainWindow", u"X", None))
        self.Editor_button.setText(QCoreApplication.translate("MainWindow", u"Editor", None))
        self.BackButton_main.setText(QCoreApplication.translate("MainWindow", u"Back", None))
        self.Current_page_label.setText("")
        self.NextButton_main.setText(QCoreApplication.translate("MainWindow", u"Next", None))
        self.ToolButton_01.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.ToolButton_02.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.ToolButton_03.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.ToolButton_04.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.ToolButton_05.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.ToolButton_06.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.ToolButton_07.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.ToolButton_08.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.ToolButton_09.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.ToolButton_10.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.ToolButton_11.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.ToolButton_12.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.Music_bttn.setText(QCoreApplication.translate("MainWindow", u"PushButton", None))
    # retranslateUi

