# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Editor.ui'
##
## Created by: Qt User Interface Compiler version 6.9.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QFontComboBox, QFrame,
    QGroupBox, QKeySequenceEdit, QLabel, QLineEdit,
    QListWidget, QListWidgetItem, QMainWindow, QPushButton,
    QSizePolicy, QStackedWidget, QTabWidget, QToolButton,
    QWidget)

class Ui_Editor_Window(object):
    def setupUi(self, Editor_Window):
        if not Editor_Window.objectName():
            Editor_Window.setObjectName(u"Editor_Window")
        Editor_Window.resize(752, 721)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Editor_Window.sizePolicy().hasHeightForWidth())
        Editor_Window.setSizePolicy(sizePolicy)
        Editor_Window.setMinimumSize(QSize(0, 0))
        Editor_Window.setMaximumSize(QSize(1024, 800))
        self.centralwidget = QWidget(Editor_Window)
        self.centralwidget.setObjectName(u"centralwidget")
        self.Edit_Button_groupBox = QGroupBox(self.centralwidget)
        self.Edit_Button_groupBox.setObjectName(u"Edit_Button_groupBox")
        self.Edit_Button_groupBox.setGeometry(QRect(10, 395, 500, 311))
        self.Edit_Button_groupBox.setCheckable(False)
        self.Edit_Button_groupBox.setChecked(False)
        self.Edit_action_tabWidget = QTabWidget(self.Edit_Button_groupBox)
        self.Edit_action_tabWidget.setObjectName(u"Edit_action_tabWidget")
        self.Edit_action_tabWidget.setGeometry(QRect(10, 180, 361, 121))
        self.Edit_action_tabWidget.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.Edit_action_tabWidget.setTabPosition(QTabWidget.TabPosition.South)
        self.shortcut_tab = QWidget()
        self.shortcut_tab.setObjectName(u"shortcut_tab")
        self.Edit_keySequenceEdit = QKeySequenceEdit(self.shortcut_tab)
        self.Edit_keySequenceEdit.setObjectName(u"Edit_keySequenceEdit")
        self.Edit_keySequenceEdit.setGeometry(QRect(10, 30, 170, 40))
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.Edit_keySequenceEdit.sizePolicy().hasHeightForWidth())
        self.Edit_keySequenceEdit.setSizePolicy(sizePolicy1)
        self.Edit_keySequenceEdit.setContextMenuPolicy(Qt.ContextMenuPolicy.DefaultContextMenu)
        self.Edit_keySequenceEdit.setClearButtonEnabled(True)
        self.Edit_keySequenceEdit.setMaximumSequenceLength(1)
        self.Add_shortcut_label = QLabel(self.shortcut_tab)
        self.Add_shortcut_label.setObjectName(u"Add_shortcut_label")
        self.Add_shortcut_label.setGeometry(QRect(10, 10, 171, 21))
        self.Edit_action_tabWidget.addTab(self.shortcut_tab, "")
        self.soft_tab = QWidget()
        self.soft_tab.setObjectName(u"soft_tab")
        self.Choose_soft_label = QLabel(self.soft_tab)
        self.Choose_soft_label.setObjectName(u"Choose_soft_label")
        self.Choose_soft_label.setGeometry(QRect(10, 10, 120, 30))
        self.Browse_pushButton = QPushButton(self.soft_tab)
        self.Browse_pushButton.setObjectName(u"Browse_pushButton")
        self.Browse_pushButton.setGeometry(QRect(140, 10, 80, 30))
        self.Soft_lineEdit = QLineEdit(self.soft_tab)
        self.Soft_lineEdit.setObjectName(u"Soft_lineEdit")
        self.Soft_lineEdit.setGeometry(QRect(10, 50, 321, 30))
        self.Edit_action_tabWidget.addTab(self.soft_tab, "")
        self.Action_tab = QWidget()
        self.Action_tab.setObjectName(u"Action_tab")
        self.Choose_action_label = QLabel(self.Action_tab)
        self.Choose_action_label.setObjectName(u"Choose_action_label")
        self.Choose_action_label.setGeometry(QRect(10, 10, 120, 30))
        self.Action_comboBox = QComboBox(self.Action_tab)
        self.Action_comboBox.setObjectName(u"Action_comboBox")
        self.Action_comboBox.setGeometry(QRect(140, 10, 201, 30))
        self.Edit_action_tabWidget.addTab(self.Action_tab, "")
        self.Edit_ico_groupBox = QGroupBox(self.Edit_Button_groupBox)
        self.Edit_ico_groupBox.setObjectName(u"Edit_ico_groupBox")
        self.Edit_ico_groupBox.setGeometry(QRect(10, 20, 361, 151))
        self.Choose_lib_icon_label = QLabel(self.Edit_ico_groupBox)
        self.Choose_lib_icon_label.setObjectName(u"Choose_lib_icon_label")
        self.Choose_lib_icon_label.setGeometry(QRect(10, 15, 81, 30))
        self.Browse_custom_pushButton = QPushButton(self.Edit_ico_groupBox)
        self.Browse_custom_pushButton.setObjectName(u"Browse_custom_pushButton")
        self.Browse_custom_pushButton.setGeometry(QRect(10, 45, 80, 30))
        self.Add_sign_label = QLabel(self.Edit_ico_groupBox)
        self.Add_sign_label.setObjectName(u"Add_sign_label")
        self.Add_sign_label.setGeometry(QRect(170, 15, 111, 30))
        self.Sign_button_lineEdit = QLineEdit(self.Edit_ico_groupBox)
        self.Sign_button_lineEdit.setObjectName(u"Sign_button_lineEdit")
        self.Sign_button_lineEdit.setGeometry(QRect(170, 45, 140, 30))
        self.Choose_custom_icon_label = QLabel(self.Edit_ico_groupBox)
        self.Choose_custom_icon_label.setObjectName(u"Choose_custom_icon_label")
        self.Choose_custom_icon_label.setGeometry(QRect(10, 75, 91, 30))
        self.Browse_lib_pushButton = QPushButton(self.Edit_ico_groupBox)
        self.Browse_lib_pushButton.setObjectName(u"Browse_lib_pushButton")
        self.Browse_lib_pushButton.setGeometry(QRect(10, 105, 80, 30))
        self.fontComboBox = QFontComboBox(self.Edit_ico_groupBox)
        self.fontComboBox.setObjectName(u"fontComboBox")
        self.fontComboBox.setGeometry(QRect(170, 105, 140, 30))
        self.line = QFrame(self.Edit_ico_groupBox)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(140, 20, 20, 121))
        self.line.setFrameShape(QFrame.Shape.VLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)
        self.Change_font = QLabel(self.Edit_ico_groupBox)
        self.Change_font.setObjectName(u"Change_font")
        self.Change_font.setGeometry(QRect(170, 75, 111, 30))
        self.Save_Button_pushButton = QPushButton(self.Edit_Button_groupBox)
        self.Save_Button_pushButton.setObjectName(u"Save_Button_pushButton")
        self.Save_Button_pushButton.setGeometry(QRect(390, 170, 101, 51))
        self.Example_toolButton = QToolButton(self.Edit_Button_groupBox)
        self.Example_toolButton.setObjectName(u"Example_toolButton")
        self.Example_toolButton.setGeometry(QRect(390, 30, 96, 96))
        self.Example_toolButton.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.Example_toolButton.setIconSize(QSize(64, 64))
        self.Example_toolButton.setCheckable(False)
        self.Example_toolButton.setChecked(False)
        self.Example_toolButton.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.Save_new_pushButton = QPushButton(self.Edit_Button_groupBox)
        self.Save_new_pushButton.setObjectName(u"Save_new_pushButton")
        self.Save_new_pushButton.setGeometry(QRect(390, 130, 101, 41))
        self.Ready_Button_listWidget = QListWidget(self.centralwidget)
        self.Ready_Button_listWidget.setObjectName(u"Ready_Button_listWidget")
        self.Ready_Button_listWidget.setGeometry(QRect(530, 10, 211, 341))
        self.Button_editor_stackedWidget = QStackedWidget(self.centralwidget)
        self.Button_editor_stackedWidget.setObjectName(u"Button_editor_stackedWidget")
        self.Button_editor_stackedWidget.setGeometry(QRect(10, 0, 511, 351))
        self.page_1 = QWidget()
        self.page_1.setObjectName(u"page_1")
        self.Button_frame = QFrame(self.page_1)
        self.Button_frame.setObjectName(u"Button_frame")
        self.Button_frame.setGeometry(QRect(0, 10, 500, 340))
        self.Button_frame.setStyleSheet(u"gridline-color: rgb(255, 170, 255);\n"
"border-color: rgb(255, 0, 255);")
        self.Button_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.Button_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.Edit_toolButton_01 = QToolButton(self.Button_frame)
        self.Edit_toolButton_01.setObjectName(u"Edit_toolButton_01")
        self.Edit_toolButton_01.setGeometry(QRect(20, 10, 96, 96))
        self.Edit_toolButton_01.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.Edit_toolButton_01.setIconSize(QSize(96, 96))
        self.Edit_toolButton_01.setCheckable(True)
        self.Edit_toolButton_01.setChecked(False)
        self.Edit_toolButton_01.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.Edit_toolButton_02 = QToolButton(self.Button_frame)
        self.Edit_toolButton_02.setObjectName(u"Edit_toolButton_02")
        self.Edit_toolButton_02.setGeometry(QRect(140, 10, 96, 96))
        self.Edit_toolButton_02.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.Edit_toolButton_02.setIconSize(QSize(96, 96))
        self.Edit_toolButton_02.setCheckable(True)
        self.Edit_toolButton_02.setChecked(False)
        self.Edit_toolButton_02.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.Edit_toolButton_03 = QToolButton(self.Button_frame)
        self.Edit_toolButton_03.setObjectName(u"Edit_toolButton_03")
        self.Edit_toolButton_03.setGeometry(QRect(260, 10, 96, 96))
        self.Edit_toolButton_03.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.Edit_toolButton_03.setIconSize(QSize(96, 96))
        self.Edit_toolButton_03.setCheckable(True)
        self.Edit_toolButton_03.setChecked(False)
        self.Edit_toolButton_03.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.Edit_toolButton_04 = QToolButton(self.Button_frame)
        self.Edit_toolButton_04.setObjectName(u"Edit_toolButton_04")
        self.Edit_toolButton_04.setGeometry(QRect(380, 10, 96, 96))
        self.Edit_toolButton_04.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.Edit_toolButton_04.setIconSize(QSize(96, 96))
        self.Edit_toolButton_04.setCheckable(True)
        self.Edit_toolButton_04.setChecked(False)
        self.Edit_toolButton_04.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.Edit_toolButton_05 = QToolButton(self.Button_frame)
        self.Edit_toolButton_05.setObjectName(u"Edit_toolButton_05")
        self.Edit_toolButton_05.setGeometry(QRect(20, 120, 96, 96))
        self.Edit_toolButton_05.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.Edit_toolButton_05.setIconSize(QSize(96, 96))
        self.Edit_toolButton_05.setCheckable(True)
        self.Edit_toolButton_05.setChecked(False)
        self.Edit_toolButton_05.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.Edit_toolButton_06 = QToolButton(self.Button_frame)
        self.Edit_toolButton_06.setObjectName(u"Edit_toolButton_06")
        self.Edit_toolButton_06.setGeometry(QRect(140, 120, 96, 96))
        self.Edit_toolButton_06.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.Edit_toolButton_06.setIconSize(QSize(96, 96))
        self.Edit_toolButton_06.setCheckable(True)
        self.Edit_toolButton_06.setChecked(False)
        self.Edit_toolButton_06.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.Edit_toolButton_07 = QToolButton(self.Button_frame)
        self.Edit_toolButton_07.setObjectName(u"Edit_toolButton_07")
        self.Edit_toolButton_07.setGeometry(QRect(260, 120, 96, 96))
        self.Edit_toolButton_07.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.Edit_toolButton_07.setIconSize(QSize(96, 96))
        self.Edit_toolButton_07.setCheckable(True)
        self.Edit_toolButton_07.setChecked(False)
        self.Edit_toolButton_07.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.Edit_toolButton_08 = QToolButton(self.Button_frame)
        self.Edit_toolButton_08.setObjectName(u"Edit_toolButton_08")
        self.Edit_toolButton_08.setGeometry(QRect(380, 120, 96, 96))
        self.Edit_toolButton_08.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.Edit_toolButton_08.setIconSize(QSize(96, 96))
        self.Edit_toolButton_08.setCheckable(True)
        self.Edit_toolButton_08.setChecked(False)
        self.Edit_toolButton_08.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.Edit_toolButton_09 = QToolButton(self.Button_frame)
        self.Edit_toolButton_09.setObjectName(u"Edit_toolButton_09")
        self.Edit_toolButton_09.setGeometry(QRect(20, 230, 96, 96))
        self.Edit_toolButton_09.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.Edit_toolButton_09.setIconSize(QSize(96, 96))
        self.Edit_toolButton_09.setCheckable(True)
        self.Edit_toolButton_09.setChecked(False)
        self.Edit_toolButton_09.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.Edit_toolButton_10 = QToolButton(self.Button_frame)
        self.Edit_toolButton_10.setObjectName(u"Edit_toolButton_10")
        self.Edit_toolButton_10.setGeometry(QRect(140, 230, 96, 96))
        self.Edit_toolButton_10.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.Edit_toolButton_10.setIconSize(QSize(96, 96))
        self.Edit_toolButton_10.setCheckable(True)
        self.Edit_toolButton_10.setChecked(False)
        self.Edit_toolButton_10.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.Edit_toolButton_11 = QToolButton(self.Button_frame)
        self.Edit_toolButton_11.setObjectName(u"Edit_toolButton_11")
        self.Edit_toolButton_11.setGeometry(QRect(260, 230, 96, 96))
        self.Edit_toolButton_11.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.Edit_toolButton_11.setIconSize(QSize(96, 96))
        self.Edit_toolButton_11.setCheckable(True)
        self.Edit_toolButton_11.setChecked(False)
        self.Edit_toolButton_11.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.Edit_toolButton_12 = QToolButton(self.Button_frame)
        self.Edit_toolButton_12.setObjectName(u"Edit_toolButton_12")
        self.Edit_toolButton_12.setGeometry(QRect(380, 230, 96, 96))
        self.Edit_toolButton_12.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.Edit_toolButton_12.setIconSize(QSize(96, 96))
        self.Edit_toolButton_12.setCheckable(True)
        self.Edit_toolButton_12.setChecked(False)
        self.Edit_toolButton_12.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.Button_editor_stackedWidget.addWidget(self.page_1)
        self.Page_control_frame_editor = QFrame(self.centralwidget)
        self.Page_control_frame_editor.setObjectName(u"Page_control_frame_editor")
        self.Page_control_frame_editor.setGeometry(QRect(130, 355, 311, 35))
        self.Page_control_frame_editor.setFrameShape(QFrame.Shape.StyledPanel)
        self.Page_control_frame_editor.setFrameShadow(QFrame.Shadow.Raised)
        self.Current_page_label_editor = QLabel(self.Page_control_frame_editor)
        self.Current_page_label_editor.setObjectName(u"Current_page_label_editor")
        self.Current_page_label_editor.setGeometry(QRect(100, 5, 60, 25))
        self.Current_page_label_editor.setContextMenuPolicy(Qt.ContextMenuPolicy.ActionsContextMenu)
        self.Current_page_label_editor.setFrameShape(QFrame.Shape.StyledPanel)
        self.Current_page_label_editor.setFrameShadow(QFrame.Shadow.Plain)
        self.Current_page_label_editor.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.NextButton_editor = QPushButton(self.Page_control_frame_editor)
        self.NextButton_editor.setObjectName(u"NextButton_editor")
        self.NextButton_editor.setGeometry(QRect(170, 5, 75, 25))
        self.BackButton_editor = QPushButton(self.Page_control_frame_editor)
        self.BackButton_editor.setObjectName(u"BackButton_editor")
        self.BackButton_editor.setGeometry(QRect(10, 5, 75, 25))
        self.Add_page_button_editor = QPushButton(self.Page_control_frame_editor)
        self.Add_page_button_editor.setObjectName(u"Add_page_button_editor")
        self.Add_page_button_editor.setGeometry(QRect(250, 5, 25, 25))
        self.Add_page_button_editor.setBaseSize(QSize(25, 25))
        self.Add_page_button_editor.setMouseTracking(False)
        self.Add_page_button_editor.setTabletTracking(False)
        self.Add_page_button_editor.setFlat(False)
        self.Remove_page_button_editor = QPushButton(self.Page_control_frame_editor)
        self.Remove_page_button_editor.setObjectName(u"Remove_page_button_editor")
        self.Remove_page_button_editor.setGeometry(QRect(280, 5, 25, 25))
        Editor_Window.setCentralWidget(self.centralwidget)

        self.retranslateUi(Editor_Window)

        self.Edit_action_tabWidget.setCurrentIndex(2)


        QMetaObject.connectSlotsByName(Editor_Window)
    # setupUi

    def retranslateUi(self, Editor_Window):
        Editor_Window.setWindowTitle(QCoreApplication.translate("Editor_Window", u"Editor Window", None))
        self.Edit_Button_groupBox.setTitle(QCoreApplication.translate("Editor_Window", u"\u0420\u0435\u0434\u0430\u043a\u0442\u0438\u0440\u043e\u0432\u0430\u043d\u0438\u0435 \u043a\u043d\u043e\u043f\u043a\u0438", None))
        self.Add_shortcut_label.setText(QCoreApplication.translate("Editor_Window", u"\u0412\u0432\u0435\u0434\u0438\u0442\u0435 \u043a\u043e\u043c\u0431\u0438\u043d\u0430\u0446\u0438\u044e \u043a\u043b\u0430\u0432\u0438\u0448:", None))
        self.Edit_action_tabWidget.setTabText(self.Edit_action_tabWidget.indexOf(self.shortcut_tab), QCoreApplication.translate("Editor_Window", u"\u0421\u043e\u0447\u0435\u0442\u0430\u043d\u0438\u0435 \u043a\u043b\u0430\u0432\u0438\u0448", None))
        self.Choose_soft_label.setText(QCoreApplication.translate("Editor_Window", u"\u0412\u044b\u0431\u0435\u0440\u0438\u0442\u0435 \u043f\u0440\u043e\u0433\u0440\u0430\u043c\u043c\u0443:", None))
        self.Browse_pushButton.setText(QCoreApplication.translate("Editor_Window", u"\u041e\u0431\u0437\u043e\u0440", None))
        self.Edit_action_tabWidget.setTabText(self.Edit_action_tabWidget.indexOf(self.soft_tab), QCoreApplication.translate("Editor_Window", u"\u041f\u0440\u043e\u0433\u0440\u0430\u043c\u043c\u0430", None))
        self.Choose_action_label.setText(QCoreApplication.translate("Editor_Window", u"\u0412\u044b\u0431\u0435\u0440\u0438\u0442\u0435 \u0434\u0435\u0439\u0441\u0442\u0432\u0438\u0435:", None))
        self.Edit_action_tabWidget.setTabText(self.Edit_action_tabWidget.indexOf(self.Action_tab), QCoreApplication.translate("Editor_Window", u"\u0414\u0435\u0439\u0441\u0442\u0432\u0438\u0435", None))
        self.Edit_ico_groupBox.setTitle(QCoreApplication.translate("Editor_Window", u"\u0412\u044b\u0431\u0435\u0440\u0438\u0442\u0435 \u0438\u043a\u043e\u043d\u043a\u0443", None))
        self.Choose_lib_icon_label.setText(QCoreApplication.translate("Editor_Window", u"\u0421\u0432\u043e\u044f \u0438\u043a\u043e\u043d\u043a\u0430:", None))
        self.Browse_custom_pushButton.setText(QCoreApplication.translate("Editor_Window", u"\u041e\u0431\u0437\u043e\u0440", None))
        self.Add_sign_label.setText(QCoreApplication.translate("Editor_Window", u"\u0414\u043e\u0431\u0430\u0432\u0438\u0442\u044c \u043f\u043e\u0434\u043f\u0438\u0441\u044c:", None))
        self.Choose_custom_icon_label.setText(QCoreApplication.translate("Editor_Window", u"\u0418\u0437 \u0431\u0438\u0431\u043b\u0438\u043e\u0442\u0435\u043a\u0438:", None))
        self.Browse_lib_pushButton.setText(QCoreApplication.translate("Editor_Window", u"\u041e\u0431\u0437\u043e\u0440", None))
        self.Change_font.setText(QCoreApplication.translate("Editor_Window", u"\u0412\u044b\u0431\u0440\u0430\u0442\u044c \u0448\u0440\u0438\u0444\u0442:", None))
        self.Save_Button_pushButton.setText(QCoreApplication.translate("Editor_Window", u"\u0421\u043e\u0445\u0440\u0430\u043d\u0438\u0442\u044c", None))
        self.Example_toolButton.setText(QCoreApplication.translate("Editor_Window", u"...", None))
        self.Save_new_pushButton.setText(QCoreApplication.translate("Editor_Window", u"\u0421\u043e\u0445\u0440\u0430\u043d\u0438\u0442\u044c\n"
"\u043a\u043d\u043e\u043f\u043a\u0443", None))
        self.Edit_toolButton_01.setText(QCoreApplication.translate("Editor_Window", u"...", None))
        self.Edit_toolButton_02.setText(QCoreApplication.translate("Editor_Window", u"...", None))
        self.Edit_toolButton_03.setText(QCoreApplication.translate("Editor_Window", u"...", None))
        self.Edit_toolButton_04.setText(QCoreApplication.translate("Editor_Window", u"...", None))
        self.Edit_toolButton_05.setText(QCoreApplication.translate("Editor_Window", u"...", None))
        self.Edit_toolButton_06.setText(QCoreApplication.translate("Editor_Window", u"...", None))
        self.Edit_toolButton_07.setText(QCoreApplication.translate("Editor_Window", u"...", None))
        self.Edit_toolButton_08.setText(QCoreApplication.translate("Editor_Window", u"...", None))
        self.Edit_toolButton_09.setText(QCoreApplication.translate("Editor_Window", u"...", None))
        self.Edit_toolButton_10.setText(QCoreApplication.translate("Editor_Window", u"...", None))
        self.Edit_toolButton_11.setText(QCoreApplication.translate("Editor_Window", u"...", None))
        self.Edit_toolButton_12.setText(QCoreApplication.translate("Editor_Window", u"...", None))
        self.Current_page_label_editor.setText("")
        self.NextButton_editor.setText(QCoreApplication.translate("Editor_Window", u"TempNext", None))
        self.BackButton_editor.setText(QCoreApplication.translate("Editor_Window", u"TempBack", None))
        self.Add_page_button_editor.setText(QCoreApplication.translate("Editor_Window", u"+", None))
        self.Remove_page_button_editor.setText(QCoreApplication.translate("Editor_Window", u"-", None))
    # retranslateUi

