# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'timer_dialog_window.ui'
##
## Created by: Qt User Interface Compiler version 6.9.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QDialog, QFrame, QHBoxLayout,
    QLayout, QSizePolicy, QToolButton, QWidget)

class Ui_Time_dialog(object):
    def setupUi(self, Time_dialog):
        if not Time_dialog.objectName():
            Time_dialog.setObjectName(u"Time_dialog")
        Time_dialog.setWindowModality(Qt.WindowModality.NonModal)
        Time_dialog.resize(550, 100)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Time_dialog.sizePolicy().hasHeightForWidth())
        Time_dialog.setSizePolicy(sizePolicy)
        Time_dialog.setMinimumSize(QSize(550, 100))
        Time_dialog.setMaximumSize(QSize(550, 100))
        font = QFont()
        font.setPointSize(12)
        Time_dialog.setFont(font)
        Time_dialog.setContextMenuPolicy(Qt.ContextMenuPolicy.NoContextMenu)
        Time_dialog.setWindowTitle(u"")
        Time_dialog.setWindowOpacity(1.000000000000000)
        Time_dialog.setSizeGripEnabled(False)
        Time_dialog.setModal(False)
        self.horizontalLayoutWidget = QWidget(Time_dialog)
        self.horizontalLayoutWidget.setObjectName(u"horizontalLayoutWidget")
        self.horizontalLayoutWidget.setGeometry(QRect(0, 0, 551, 101))
        self.horizontalLayout = QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setSizeConstraint(QLayout.SizeConstraint.SetMaximumSize)
        self.horizontalLayout.setContentsMargins(6, 4, 6, 4)
        self.Timer_but_frame = QFrame(self.horizontalLayoutWidget)
        self.Timer_but_frame.setObjectName(u"Timer_but_frame")
        self.Timer_but_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.Timer_but_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.Timer_buton_2 = QToolButton(self.Timer_but_frame)
        self.Timer_buton_2.setObjectName(u"Timer_buton_2")
        self.Timer_buton_2.setGeometry(QRect(100, 10, 70, 70))
        self.Timer_buton_2.setMinimumSize(QSize(70, 70))
        self.Timer_buton_2.setMaximumSize(QSize(70, 70))
        self.Timer_buton_2.setBaseSize(QSize(70, 70))
        font1 = QFont()
        font1.setPointSize(12)
        font1.setBold(True)
        font1.setStyleStrategy(QFont.PreferAntialias)
        self.Timer_buton_2.setFont(font1)
        self.Timer_buton_2.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.Timer_buton_2.setContextMenuPolicy(Qt.ContextMenuPolicy.NoContextMenu)
        self.Timer_buton_2.setIconSize(QSize(96, 96))
        self.Timer_buton_2.setCheckable(False)
        self.Timer_buton_2.setChecked(False)
        self.Timer_buton_2.setAutoRepeatDelay(600)
        self.Timer_buton_2.setAutoRepeatInterval(300)
        self.Timer_buton_2.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextBesideIcon)
        self.Timer_buton_2.setAutoRaise(False)
        self.Timer_buton_2.setArrowType(Qt.ArrowType.NoArrow)
        self.Timer_buton_1 = QToolButton(self.Timer_but_frame)
        self.Timer_buton_1.setObjectName(u"Timer_buton_1")
        self.Timer_buton_1.setGeometry(QRect(10, 10, 70, 70))
        self.Timer_buton_1.setMinimumSize(QSize(70, 70))
        self.Timer_buton_1.setMaximumSize(QSize(70, 70))
        self.Timer_buton_1.setBaseSize(QSize(70, 70))
        self.Timer_buton_1.setFont(font1)
        self.Timer_buton_1.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.Timer_buton_1.setContextMenuPolicy(Qt.ContextMenuPolicy.NoContextMenu)
        self.Timer_buton_1.setIconSize(QSize(96, 96))
        self.Timer_buton_1.setCheckable(False)
        self.Timer_buton_1.setChecked(False)
        self.Timer_buton_1.setAutoRepeatDelay(600)
        self.Timer_buton_1.setAutoRepeatInterval(300)
        self.Timer_buton_1.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextBesideIcon)
        self.Timer_buton_1.setAutoRaise(False)
        self.Timer_buton_1.setArrowType(Qt.ArrowType.NoArrow)
        self.Timer_buton_6 = QToolButton(self.Timer_but_frame)
        self.Timer_buton_6.setObjectName(u"Timer_buton_6")
        self.Timer_buton_6.setGeometry(QRect(460, 10, 70, 70))
        self.Timer_buton_6.setMinimumSize(QSize(70, 70))
        self.Timer_buton_6.setMaximumSize(QSize(70, 70))
        self.Timer_buton_6.setBaseSize(QSize(70, 70))
        self.Timer_buton_6.setFont(font1)
        self.Timer_buton_6.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.Timer_buton_6.setContextMenuPolicy(Qt.ContextMenuPolicy.NoContextMenu)
        self.Timer_buton_6.setIconSize(QSize(96, 96))
        self.Timer_buton_6.setCheckable(False)
        self.Timer_buton_6.setChecked(False)
        self.Timer_buton_6.setAutoRepeatDelay(600)
        self.Timer_buton_6.setAutoRepeatInterval(300)
        self.Timer_buton_6.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextBesideIcon)
        self.Timer_buton_6.setAutoRaise(False)
        self.Timer_buton_6.setArrowType(Qt.ArrowType.NoArrow)
        self.Timer_buton_3 = QToolButton(self.Timer_but_frame)
        self.Timer_buton_3.setObjectName(u"Timer_buton_3")
        self.Timer_buton_3.setGeometry(QRect(190, 10, 70, 70))
        self.Timer_buton_3.setMinimumSize(QSize(70, 70))
        self.Timer_buton_3.setMaximumSize(QSize(70, 70))
        self.Timer_buton_3.setBaseSize(QSize(70, 70))
        self.Timer_buton_3.setFont(font1)
        self.Timer_buton_3.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.Timer_buton_3.setContextMenuPolicy(Qt.ContextMenuPolicy.NoContextMenu)
        self.Timer_buton_3.setIconSize(QSize(96, 96))
        self.Timer_buton_3.setCheckable(False)
        self.Timer_buton_3.setChecked(False)
        self.Timer_buton_3.setAutoRepeatDelay(600)
        self.Timer_buton_3.setAutoRepeatInterval(300)
        self.Timer_buton_3.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextBesideIcon)
        self.Timer_buton_3.setAutoRaise(False)
        self.Timer_buton_3.setArrowType(Qt.ArrowType.NoArrow)
        self.Timer_buton_4 = QToolButton(self.Timer_but_frame)
        self.Timer_buton_4.setObjectName(u"Timer_buton_4")
        self.Timer_buton_4.setGeometry(QRect(280, 10, 70, 70))
        self.Timer_buton_4.setMinimumSize(QSize(70, 70))
        self.Timer_buton_4.setMaximumSize(QSize(70, 70))
        self.Timer_buton_4.setBaseSize(QSize(70, 70))
        self.Timer_buton_4.setFont(font1)
        self.Timer_buton_4.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.Timer_buton_4.setContextMenuPolicy(Qt.ContextMenuPolicy.NoContextMenu)
        self.Timer_buton_4.setIconSize(QSize(96, 96))
        self.Timer_buton_4.setCheckable(False)
        self.Timer_buton_4.setChecked(False)
        self.Timer_buton_4.setAutoRepeatDelay(600)
        self.Timer_buton_4.setAutoRepeatInterval(300)
        self.Timer_buton_4.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextBesideIcon)
        self.Timer_buton_4.setAutoRaise(False)
        self.Timer_buton_4.setArrowType(Qt.ArrowType.NoArrow)
        self.Timer_buton_5 = QToolButton(self.Timer_but_frame)
        self.Timer_buton_5.setObjectName(u"Timer_buton_5")
        self.Timer_buton_5.setGeometry(QRect(370, 10, 70, 70))
        self.Timer_buton_5.setMinimumSize(QSize(70, 70))
        self.Timer_buton_5.setMaximumSize(QSize(70, 70))
        self.Timer_buton_5.setBaseSize(QSize(70, 70))
        self.Timer_buton_5.setFont(font1)
        self.Timer_buton_5.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.Timer_buton_5.setContextMenuPolicy(Qt.ContextMenuPolicy.NoContextMenu)
        self.Timer_buton_5.setIconSize(QSize(96, 96))
        self.Timer_buton_5.setCheckable(False)
        self.Timer_buton_5.setChecked(False)
        self.Timer_buton_5.setAutoRepeatDelay(600)
        self.Timer_buton_5.setAutoRepeatInterval(300)
        self.Timer_buton_5.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextBesideIcon)
        self.Timer_buton_5.setAutoRaise(False)
        self.Timer_buton_5.setArrowType(Qt.ArrowType.NoArrow)

        self.horizontalLayout.addWidget(self.Timer_but_frame)


        self.retranslateUi(Time_dialog)

        QMetaObject.connectSlotsByName(Time_dialog)
    # setupUi

    def retranslateUi(self, Time_dialog):
        self.Timer_buton_2.setText(QCoreApplication.translate("Time_dialog", u"2 \u043c", None))
        self.Timer_buton_1.setText(QCoreApplication.translate("Time_dialog", u"1 \u043c", None))
        self.Timer_buton_6.setText(QCoreApplication.translate("Time_dialog", u"15 \u043c", None))
        self.Timer_buton_3.setText(QCoreApplication.translate("Time_dialog", u"3 \u043c", None))
        self.Timer_buton_4.setText(QCoreApplication.translate("Time_dialog", u"5 \u043c", None))
        self.Timer_buton_5.setText(QCoreApplication.translate("Time_dialog", u"10 \u043c", None))
        pass
    # retranslateUi

